title: Your Sport Site
locale: en_GB

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - bin/
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - lib/
  - Makefile
  - node_modules/
  - package-lock.json
  - package.json
  - vendor/*

sass:
  silence_deprecations:
    - color-functions
    - global-builtin
    - import
    - mixed-decls
  style: compressed
